### ISSUE TITLE
Failure to retrieve artifacts

### ISSUE THREAD

**Issue by rob94110** [fgrosse/go-coverage-report#22]
The action is failing for me, apparently because there are no artifacts available in the target branch (not surprising because this is the first attempt to run it).

```
Download code coverage results from target branch
  ++ gh run list --status=success --branch=main --workflow=Build --event=push --json=databaseId --limit=1 -q '.[] | .databaseId'
  + LAST_SUCCESSFUL_RUN_ID=8953089596
  + '[' -z 8953089596 ']'
  + gh run download 8953089596 --name=code-coverage --dir=.github/outputs
  no valid artifacts found to download
  Error: Process completed with exit code 1.
```

Is there some set up/configuration step that I've missed?

Thanks,

Rob.

**Comment by fgrosse** [comment]
Hi Rob, so far, the action will always fail if there is no baseline coverage to compare to (like in your case). What you can do is to merge changes already that will collect and upload these on the target branch. Then in a second step you can enable the coverage report.

**Comment by rob94110** [comment]
Thanks!  Looks like it's working now.

**Comment by Vishalks** [comment]
@fgrosse I am getting error:

`Download code coverage results from current run
  error fetching artifacts: HTTP 403: Resource not accessible by integration (https://api.github.com/repos/Remitly/sov-osiris/actions/runs/9117636729/artifacts?per_page=100)
  Error: Process completed with exit code 1.`

Can you advise as to what's going wrong with my setup?

**Comment by Vishalks** [comment]
@rob94110 I am getting the same error as you. What did you end up doing to solve it? cc: @fgrosse

**Comment by rob94110** [comment]
Hi Vishal, I commented out the `code_coverage` part of the action and then merged the pull request.  And then I uncommented it and did a second pull request.
