### ISSUE TITLE
Annotate uncovered statements with warnings

### ISSUE THREAD

**Issue by ilya-hontarau** [fgrosse/go-coverage-report#31]
Add warnings for code changes in pull requests that dont have test coverage.

**Comment by fgrosse** [comment]
Can you elaborate on what kind of change you are suggesting? Currently, if Go files were changed, this action will already show the impact on the unit test coverage of the repository.

**Comment by ilya-hontarau** [comment]
I think it can be done in the way [codecov does](https://docs.codecov.com/docs/github-checks) and [golangci lint](https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#golangci-lint-action)

**Comment by fgrosse** [comment]
Thanks for the suggestion, now I see what you mean.

To be honest, the scope of this GitHub action is to provide a high level summary of the changes with a single comment. What you are suggesting sounds interesting but is far beyond that scope. If you would like to have more elaborate features around code coverage, you are probably better of using codecov or another dedicated service for code coverage :sweat_smile:
