### ISSUE TITLE
Support generating comment as an output instead of posting it directly

### ISSUE THREAD

**Issue by jshufro** [fgrosse/go-coverage-report#34]
I'm also uploading the html coverage report, and would like to append the artifact URL to the comment this action leaves, before posting the comment myself.

**Comment by fgrosse** [comment]
Nice idea, and shouldn't be too difficult to implement given the comment is [already written into a file][1].

Would you like to give it a try and submit a PR? 

[1]: https://github.com/fgrosse/go-coverage-report/blob/main/scripts/github-action.sh
