### ISSUE TITLE
deleted files not counted in all_changed_files.json

### ISSUE THREAD

**Issue by jshufro** [fgrosse/go-coverage-report#35]
Discovered while working on https://github.com/fgrosse/go-coverage-report/issues/34 that I can straight delete a test file and no coverage comment is generated.

This is because tj-actions/changed_files specifically excludes deleted files from the all_changed_files json:
![image](https://github.com/user-attachments/assets/4de448ab-5909-4a15-a72c-1b92edb9b13f)

all_modified_files includes the deletions, and makes it so we correctly detect decreased coverage from deleting tests.

Working on a PR alongside the above issue.

**Comment by fgrosse** [comment]
Good catch!
